### ISSUE TITLE
Update for revision?

### ISSUE THREAD

**Issue by ghost** [MadPidgeon/Babai-Graph-Isomorphism#1]
I have a lot of reading to do before I am ready to understand your thesis and then the actual paper, but I noticed Babai updated the paper. http://people.cs.uchicago.edu/~laci/update.html

**Comment by MadPidgeon** [comment]
I am aware of the update, and I haven't looked into it much yet simply because the changes are in a part I haven't treated in my thesis.
Perhaps I'll try to add some code for the design lemma some time in the future if I can make it work.

**Comment by ghost** [comment]
Okay I will close, sounds irrelevant for now
